# Numpy Introduction

In [1]:
#pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np
a= np.arange(10) # 1D array (10 elements)
print(a.shape)
print(a)

(10,)
[0 1 2 3 4 5 6 7 8 9]


In [4]:
a2 = a[np.newaxis, :] # 2D array (1 row, 10 columns)
print(a2.shape)
print(a2)

(1, 10)
[[0 1 2 3 4 5 6 7 8 9]]


In [6]:
a3 = a2[np.newaxis, :] # 3D array (1 plane, 1 row, 10 columns)
print(a3.shape)
print(a3)

(1, 1, 10)
[[[0 1 2 3 4 5 6 7 8 9]]]


In [18]:
# type of array
type(a) # numpy. n dimensional array 

numpy.ndarray

In [17]:
# data type of array elements
b.dtype

dtype('int32')

## Creating Arrays with numpy

In [7]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = np.array([(11, 12, 13, 14, 15, 16, 17, 18, 19, 20), (21, 22, 23, 24, 25, 26, 27, 28, 29, 30)])
print(a.shape)
print(b.shape)

(10,)
(2, 10)


In [11]:
print(b)

[[11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


## Initialize Arrays

In [12]:
zeros = np.zeros((3, 4)) #(rows and columns)
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
zeros.dtype

dtype('float64')

In [13]:
ones = np.ones((3, 4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
full = np.full((3, 4), 5)
print(full)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [15]:
# Identity Matrix
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Attributes of Array

In [19]:
b.shape

(2, 10)

In [23]:
len(b) # return the length of elements

2

In [21]:
b.ndim # return the dimension of the array

2

In [25]:
b.size # return the total no of elements

20

## Basic Operations

In [26]:
g = a -b  # subtraction
print(g)

[[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
 [-20 -20 -20 -20 -20 -20 -20 -20 -20 -20]]


In [27]:
h = a+b # addition
print(h)

[[12 14 16 18 20 22 24 26 28 30]
 [22 24 26 28 30 32 34 36 38 40]]


In [28]:
h1 = np.add(a, b) # addition
print(h1)

[[12 14 16 18 20 22 24 26 28 30]
 [22 24 26 28 30 32 34 36 38 40]]


In [29]:
f = a*b # multiplication
print(f)

[[ 11  24  39  56  75  96 119 144 171 200]
 [ 21  44  69  96 125 156 189 224 261 300]]


In [30]:
j = a/b # division
print(j)

[[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
  0.41176471 0.44444444 0.47368421 0.5       ]
 [0.04761905 0.09090909 0.13043478 0.16666667 0.2        0.23076923
  0.25925926 0.28571429 0.31034483 0.33333333]]


In [32]:
# square of each element
k = b**2
print(k)

[[121 144 169 196 225 256 289 324 361 400]
 [441 484 529 576 625 676 729 784 841 900]]
