In [1]:
import numpy as np
# empty array (ehich is near to zero)
empty = np.empty([3, 2])
print(empty)
print ("Printing only the first element: ")
print(empty[0]) #it will print only the first row

[[1.e-323 0.e+000]
 [0.e+000 0.e+000]
 [0.e+000 0.e+000]]
Printing only the first element: 
[1.e-323 0.e+000]


In [3]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [5]:
# array of even numbers from 0 to 23 
even = np.arange(0, 23 , 2) # (0 to 23 with step 2) all even numbers
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [6]:
# array of odd numbers from 0 to 23
odd = np.arange(1, 23, 2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [7]:
# specific difference between numbers
diff = np.arange(0, 23, 3)
diff

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [11]:
lin = np.linspace(0, 10, num= 10) # gives a linear trend from 0 to 10
lin

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [12]:
lin.dtype

dtype('float64')

In [17]:
# define the data type of array
a = np.arange(0, 22.6 , 1.5 ,dtype = np.int64)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int64)

In [19]:
# sorting an array
arr = np.array([1,3,2,4,6,8,9,5,7,10])
arr.sort()
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Concatenation

In [21]:
# concatenate two arrays
a = np.array([1,3,2,4,5])
b = np.array([6,7,8,9,10])
arr = np.concatenate((a,b))
arr

array([ 1,  3,  2,  4,  5,  6,  7,  8,  9, 10])

In [22]:
# concatenate 2D arrays
x = np.array([[1, 2], [3, 4]]) # 2x2 matrix
y = np.array([[5, 6]])  # 1x2 matrix
np.concatenate((x,y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
w = np.array([[1, 2], [4, 5]]) # 2x2 matrix
x = np.array([[1, 2], [3, 4]]) # 2x2 matrix
z = np.concatenate((x,w), axis = 1) # axis 1 means columns will change and axis 0 means rows will change
z

array([[1, 2, 1, 2],
       [3, 4, 4, 5]])

In [28]:
# 3d array
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [29]:
array_example.ndim

3

In [30]:
array_example.size

24

In [31]:
len(array_example)

3

In [32]:
array_example.shape

(3, 2, 4)

In [37]:
# create an array of size (3,1,4)

h = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7],
                           [8,9,10,11]]])
h.ndim
h.shape


(1, 3, 4)

In [39]:
# reshape array
h1 = h.reshape(4,3)
h1.shape

(4, 3)

In [40]:
h1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
h1.reshape(3,1,4)

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [47]:
# create 1D array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
a.shape

(12,)

In [48]:
# convert that into 2D
b = a[np.newaxis, :]
b.shape

(1, 12)

In [50]:
c = a[:, np.newaxis]
c.shape

(12, 1)

## Indexing and Slicing

In [51]:
a= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [54]:
# a[from : to]
a[2:5]

array([3, 4, 5])

In [55]:
a[-4:] # last 4 elements

array([ 9, 10, 11, 12])

In [56]:
a[-4:-1]

array([ 9, 10, 11])

In [57]:
# a 2D array
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
b[0]

array([1, 2, 3, 4])

In [59]:
b[1: , 1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [61]:
b[b<=5]

array([1, 2, 3, 4, 5])

In [62]:
b[b%2==0] # Filter even numbers

array([ 2,  4,  6,  8, 10, 12])

In [63]:
b[b%2==1] # Filter odd numbers

array([ 1,  3,  5,  7,  9, 11])

In [64]:
# use two conditions
b[(b>3) & (b<10)]

array([4, 5, 6, 7, 8, 9])

In [65]:
# user 3 conditions and filter the arrays
b[(b>3) & (b<10) & (b%2==0)]

array([4, 6, 8])

In [66]:
b[(b>3) | (b<10)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

##  Making an array from data or another array

In [68]:
a = np.arange(0, 222, 5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [69]:
len(a)

45

In [70]:
arr1 = a[40:45]
arr1

array([200, 205, 210, 215, 220])

In [74]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b = np.array([0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22]) 
c= np.vstack((a,b)) # Stack arrays in sequence vertically (row wise)
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22]])

In [75]:
d= np.hstack((a,b)) # Stack arrays in sequence horizontally (column wise)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  0,  2,  4,  6,  8,
       10, 12, 14, 16, 18, 20, 22])

In [76]:
d = d.reshape(3,8)
d

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  0,  2,  4,  6],
       [ 8, 10, 12, 14, 16, 18, 20, 22]])

## Matrix or Matrices

In [77]:
# create a 2x3 matrix
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
b = np.arange(0 , 100 , 2).reshape(5, 10)
b 

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [87]:
# slicing a matrix
# b[rows , columns]
c =b[0:3, 3:5]
c

array([[ 6,  8],
       [26, 28],
       [46, 48]])

In [88]:
i = b[0:4, 6:8]
i

array([[12, 14],
       [32, 34],
       [52, 54],
       [72, 74]])

In [89]:
# max value in matrix
b.max()

98

In [90]:
# min value in matrix
b.min()

0

In [91]:
# sum of whole matrix
b.sum()

2450

In [93]:
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [92]:
# max value only for columns
b.max(axis = 0)

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [94]:
# max value only for rows
b.max(axis = 1)

array([18, 38, 58, 78, 98])

In [98]:
m = np.arange(0 , 20 , 2).reshape(5, 2)
m

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [100]:
# to add values with all matrix elements
m + np.array([20 ,22]) # same method foe sub , mul , div , mod

array([[20, 24],
       [24, 28],
       [28, 32],
       [32, 36],
       [36, 40]])

In [101]:
np.vstack((m , np.array([42 ,44])))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [42, 44]])

In [102]:
np.flip(b) # reverse the matrix 

array([[98, 96, 94, 92, 90, 88, 86, 84, 82, 80],
       [78, 76, 74, 72, 70, 68, 66, 64, 62, 60],
       [58, 56, 54, 52, 50, 48, 46, 44, 42, 40],
       [38, 36, 34, 32, 30, 28, 26, 24, 22, 20],
       [18, 16, 14, 12, 10,  8,  6,  4,  2,  0]])